name: DART Auto Updater

on:
  schedule:
    # 1. KST 07:30 ~ 07:50 (UTC 22:30 ~ 22:50)
    - cron: '30-59/10 22 * * 1-5' 
    # 2. KST 08:00 ~ 19:50 (UTC 23:00 ~ 10:50)
    - cron: '*/10 23,0-10 * * 1-5'
    # 3. KST 20:00 (UTC 11:00)
    - cron: '0 11 * * 1-5'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v4

    - name: 파이썬 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 패키지 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 파이썬 스크립트 실행
      env:
        DART_API_KEY: ${{ secrets.DART_API_KEY }}
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: |
        python main.py
